- code/DocumentationManifest.php
- code/controllers/DocumentationViewer.php
- code/models/DocumentationEntity.php
- docs/en/configuration.md
Found that if you set your version on an entity to anything other than the actual name of the git branch the edit link button would be broken.
This fixes this issue by allowing a optional Branch name to be set in the config. Defaults to the version unless branch is set.
> ENHANCEMENT optional branch property to allow version aliases.

- code/forms/DocumentationSearchForm.php
From a UX POV, when I'm searching docs I'm likely to be working on a site of a specific version - results of docs from older or newer versions are likely to be less relevant to me. 
If I want to search wider after my initial search I can use the check boxes on the advanced search.
I feel it's a reasonable assumption that a search when I'm on a specific version should return results from that version only.
> Pass the current version to the search

- css/layout.css
All info boxes in docs that use the 'hint' css class as recommended are currently missing a coloured background.
> FIX hint styling

- css/typography.css
If you hover on the headers at the moment, the anchor indicator doesn't show unless you hover on where it is, which isn't very discoverable.
This fixes that problem
> Fixing issue where anchor idicator does not show on hover

- .travis.yml
We haven't addressed this module for 3.2 compat yet but added more versions of php for 3.1 core.
> Test more php versions and 3.2 core

- code/DocumentationManifest.php
This allows things like styling or highlighting of the currentl stable version when used in a project to make it more obvious that people should be using that documentation.
> Add a way to check if a version is the current stable

- code/DocumentationParser.php
Links in backticks are temporarily written with SS characters inserted to stop further parsing. However, some class names have SS in them so this must be changed to something less likely to be in a class name: XYZ
> fixed rewrite_api_links() to handle SS in class names with backticks

- code/controllers/DocumentationViewer.php
- tests/DocumentationViewerTest.php
With documentation in the default location (dev/docs/en/) it appears that in some cases the redirect from say dev/docs/en/my-module/my-doc-file.md to dev/docs/en/my-module/my-doc-file/ will end up being incorrectly redirected to dev/docs/my-module/dev/docs/my-module/my-doc-file/. This pull request simply changes the redirect to use an absolute url instead.
> BUGFIX: Fixed redirecting to strip extensions incorrectly redirecting

- code/DocumentationHelper.php
- code/DocumentationManifest.php
- code/DocumentationParser.php
- code/models/DocumentationPage.php
When using the module on windows DIRECTORY_SEPERATOR returns a backslash instead of a forward slash. This causes one primary issue, an infinite loop when getMenu() is called causing the memory limit to be reached. It also seems to cause issues doing other tasks like adjusting the links to relative files. Issue #70 is related to and fixed by this pull request.
> BUGFIX: Fixed issues related to windows filesystem using backslash instead of forward slash

- code/controllers/DocumentationViewer.php
When viewing the "Documentation Index" links do not point inside of the base link for the documentation. For example links will appear as http://example.com/en/docviewer/ rather than the expected http://example.com/dev/docs/en/docviewer/ resulting in a 404 when clicked if the base link is anything other than the site root.
> BUGFIX: Links in the all pages view missing the documentation base link

- code/DocumentationManifest.php
When viewing a documentation article the next/previous page buttons do not point inside of the base link for the documentation. For example links will appear as http://example.com/en/docviewer/ rather than the expected http://example.com/dev/docs/en/docviewer/ resulting in a 404 when clicked if the base link is anything other than the site root.
> BUGFIX: Fixed issue next/previous page links missing the documentation base link

- code/DocumentationHelper.php
- code/DocumentationParser.php
Looks like I introduced a bug in 1556c77d2713732cce34dc1941b627116c7c707c on windows when the DocumentationParser tries to remap images and file links. Basically Director::makeRelative() checks before it makes the file system path relative since we're making the paths normalized it never matches the value of Director::baseFolder(). Which makes the path never made relative on windows. This pull request adds a new helper method to make these normalized paths relative using the same idea as what Director::makeRelative() would normally do.
I looked for another way to do this without regressing back to the infinite loop we had before 1556c77d2713732cce34dc1941b627116c7c707c  but I couldn't come up with away to make it work.
> BUGFIX: Fixed issue generating image paths on windows

- code/models/DocumentationPage.php
This pull request fixes a warning generated from file_get_contents when viewing a folder that has no index.md caused by DocumentationPage.php trying to use file_get_contents() on a folder when attempting to get the Introduction.
> BUGFIX: Fixed file_get_contents warning when viewing a folder that has no index.md

- code/DocumentationManifest.php
- code/controllers/DocumentationViewer.php
- templates/Includes/DocumentationSidebar.ss
Due to the location of the "Home" link for every module that the documentation covers it creates a duplicate link labeled "Home" this pull request moves the "Home" link outside the Menu loop which creates it only once with a link to the docs home.
> BUGFIX: Fixed duplicate Home links appearing

- code/DocumentationParser.php
This pull request fixes a case where the image urls could end up having a backslash on windows, which was causing the DocumentationParserTest to fail.
> BUGFIX: Fixed case where image urls could end up having a backslash on windows

- code/DocumentationParser.php
- javascript/DocumentationViewer.js
- tests/DocumentationParserTest.php
- tests/docs/en/test.md
This pull requests fixes the relative anchors on pages like https://docs.silverstripe.org/en/3.3/changelogs/3.2.0/ and resolves issue #104.
> BUGFIX: Fixed incorrectly formed page specific anchor links (fixes #104)

- README.md
- code/DocumentationManifest.php
- code/tasks/CheckDocsSourcesTask.php
- composer.json
- docs/en/configuration.md
In the past, deployments will cause the site to continually fail, until a source file update is successfully run.
In always-up environments, this isn't really ideal, so this error has been changed to a warning. If a sources dir isn't available, it will be treated as removed until such time as the sources become available.
A dev task dev/tasks/CheckDocsSourcesTask has been created to ensure that warnings can be discovered during live deployments.
> ENHANCEMENT A missing sources dir will simply disable that repo with a warning

- code/DocumentationParser.php
This tweak fixes parsing of documents with Windows line endings. Currently these files lose most of their blank lines and end up with IDs on the line after headings, causing the Markdown parser to return some very odd results.
You can see an example of the current behaviour [here](https://www.cwp.govt.nz/developer-docs/en/1.3/how_tos/caching/).
> Added support for variable line endings.

- code/controllers/DocumentationViewer.php
See https://code.google.com/archive/p/google-code-prettify and https://github.com/google/code-prettify
This affects doc.silverstripe.org so the live site will need to be updated.
> Updated invalid url for syntax highligter

- css/layout.css
Noticed problem when using docsviewer on a site I am developing. Common problem. Easy fix.
Quite visible if (i) a page's content fits within the browser window's height when the table of contents dropdown is closed but (ii) the content no longer fits vertically when the table of contents dropdown is opened. When the dropdown is opened, a vertical scroll bar appears in the browser and the page's horizontal alignment shifts by the scroll bar width.  
@frankmullenger FYI: I also noticed this in swipestripe docs :)
> FIX horizontal alignment shifts when vertical scroll bar appears

- css/layout.css
- css/typography.css
- javascript/DocumentationViewer.js
- templates/DocumentationViewer.ss
- templates/DocumentationViewer_all.ss
- templates/DocumentationViewer_results.ss
- templates/Includes/DocumentationBreadcrumbs.ss
- templates/Includes/DocumentationSidebar.ss
- templates/Includes/DocumentationTableContents.ss
Reported in #120 - when in mobile view, you cannot access the docs contents menu to move around the documentation. This adds a basic hamburger type button when at the mobile break point in the css that can be clicked and then the side bar nav slides in from the left for the mobile user.
> Create sidebar hamburger menu for mobile

- code/DocumentationParser.php
- code/models/DocumentationPage.php
- tests/DocumentationParserTest.php
- tests/docs-parser/en/MetaDataTest.md
Sometimes intro meta data is long and needs to go on multiple lines.
This fix allows meta data to run over multiple lines.
> FIX Allow multi-line headers

- css/highlight.css
- css/layout.css
- css/typography.css
Resolves https://github.com/silverstripe/doc.silverstripe.org/issues/164
Reference #134 #139
After discussion with @clarkepaul we decided to keep the lighter code block colours due to being easier on the eye as a whole for the page. With the dark background they are easier to read individually but when viewing the page as a whole it is quite distracting with the ever changing background. This could be down to individual preference, but hopefully, this is still a step forward.
> NEW Adjust docs colours to be web accessible

- code/DocumentationManifest.php
What currently happens is the manifest loops all versions and adds redirects for each version to handle versionless URLs to redirect to that version's equivalent, but will overwrite existing entries. Since 4 (in docs.silverstripe.org) is registered before 3, the result ends up with canonicals with 3 instead of 4 (desired).
> FIX Ensure first processed stable version is treated as canonical

- css/typography.css
Sorry, this was my mistake, will create a separate P.R to address footer license image.
Fixes: https://github.com/silverstripe/doc.silverstripe.org/issues/171 and https://github.com/silverstripeltd/ssorg/issues/56
> FIX Remove image styles - revert to original

- .travis.yml
- composer.json
Dependency for parsedown increased to minor semver version ~1.1 . Reason: other modules that require parsedown as dependency need higher version of it.
> Newer parsedown requirement; PHP 7 support

- code/controllers/DocumentationViewer.php
In some cases the Lang is not available in the route, this fixes that as well as making the getEditLink() method extensible
> FIX getEditLink is now extensible and Lang route handling has a fallback

- .travis.yml
- javascript/DocumentationViewer.js
From jQuery 1.7.2 docs:
> This method is a shortcut for `.on( "load", handler )`
https://api.jquery.com/load-event/#load-handler
This method was deprecated in jQuery 1.8, getting in the way of jQuery 3 upgrade.
This is a backwards compatible change and can be merged into master and downmerged to v2 because:
* This module requires SS Framework 3, regardless of branch.
* SS Framework 3 bundles jQuery 1.7.2.
* 1.7.2 supports the `on` handler.
> jQuery 3 compatibility.
